# Generated by Django 4.2.11 on 2024-04-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notificationsLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('dt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='semFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_sub', models.CharField(choices=[('M4', 'M4'), ('DAA', 'DAA'), ('MCES', 'MCES'), ('OS', 'OS'), ('OOPS', 'OOPS'), ('KANNADA', 'KANNADA')], max_length=100)),
                ('module_name', models.IntegerField()),
                ('pdf_module', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='semOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_sub', models.CharField(choices=[('M1', 'M1'), ('CHEMISTRY', 'CHEMISTRY'), ('ELN', 'ELN'), ('CPS', 'CPS'), ('MECH', 'MECH'), ('ENGLISH', 'ENGLISH')], max_length=100)),
                ('module_name', models.IntegerField()),
                ('pdf_module', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='semThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_sub', models.CharField(choices=[('M3', 'M3'), ('DSA', 'DSA'), ('CO', 'CO'), ('ADE', 'ADE'), ('DMS', 'DMS'), ('KANNADA', 'KANNADA')], max_length=100)),
                ('module_name', models.IntegerField()),
                ('pdf_module', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='semTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_sub', models.CharField(choices=[('M2', 'M2'), ('PHYSICS', 'PHYSICS'), ('ELE', 'ELE'), ('CIVIL', 'CIVIL'), ('EGDL', 'EGDL'), ('ENGLISH', 'ENGLISH')], max_length=100)),
                ('module_name', models.IntegerField()),
                ('pdf_module', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
